import type { Metadata } from "next";
import { Geist, Geist_Mono, Bebas_Neue } from "next/font/google";
import "./globals.css";

const bebas = Bebas_Neue({
  variable: "--font-bebas",
  subsets: ["latin"],
  weight: "400", // Bebas only has 400
});

export const metadata: Metadata = {
  title: "STORYTELLER",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${bebas.variable}
          antialiased bg-[#DCCFEC] py-4
        `}
      >
        {children}
      </body>
    </html>
  );
}
